=== irods/irods/configuration_schemas/v4/client_hints.json
{
    "id": "file:///var/lib/irods/configuration_schemas/v4/client_hints.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "hash_scheme": {"type": "string", "enum": ["md5", "sha256"]},
        "match_hash_policy": {"type": "string", "enum": ["strict", "compatible"]},
        "specific_queries": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "strict_acls": {"type": "string", "enum": ["on", "off"]}
    },
    "required": [
        "hash_scheme",
        "match_hash_policy",
        "specific_queries",
        "strict_acls"
    ]
}

=== irods/irods/schemas/configuration/samples/sample-client_hints.json
{
    "strict_acls": "on",
    "specific_queries": [
        "ls",
        "lsl",
        "ShowCollAcls",
        "listQueryByAliasLike",
        "findQueryByAlias",
        "ilsLACollections",
        "ilsLADataObjects",
        "listSharedCollectionsOwnedByUser",
        "listSharedCollectionsSharedWithUser",
        "listUserACLForDataObjViaGroup",
        "listUserACLForCollectionViaGroup",
        "DataObjInCollReCur"
    ],
    "hash_scheme": "sha256",
    "match_hash_policy": "compatible"
}
