=== irods/irods/configuration_schemas/v4/VERSION.json
{
    "id": "file:///var/lib/irods/configuration_schemas/v4/VERSION.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "catalog_schema_version": {"type": "integer" },
        "commit_id": {"type": "string", "pattern": "^[0-9a-f]{40}$"},
        "configuration_schema_version": {"type": "integer" },
        "installation_time": {"type": "string", "format": "date-time"},
        "irods_version": {"type": "string"},
        "previous_version": {
            "$ref": "VERSION.json"
        }
    },
    "required": [
        "catalog_schema_version",
        "commit_id",
        "configuration_schema_version",
        "irods_version"
    ]
}

=== irods/irods/schemas/configuration/samples/sample-version.json
{
    "catalog_schema_version": 4,
    "commit_id": "50f13f0c7c9f75e06e79f760e3b979363b777027",
    "configuration_schema_version": 2,
    "installation_time": "2015-06-05T21:12:54Z",
    "irods_version": "4.1.2",
    "previous_version": {
        "catalog_schema_version": 3,
        "commit_id": "77be27207aa3b191d2962d04f89e0d72b7253205",
        "configuration_schema_version": 1,
        "installation_time": "2014-08-20T17:36:40Z",
        "irods_version": "4.0.3"
    }
}
